### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kpu** [hainan-xv/zipporah#3]
Can you add a license to the repository?

**Comment by kpu** [comment]
Ping @phikoehn

**Comment by phikoehn** [comment]
What license do you suggest?

**Comment by kpu** [comment]
I'm sure @mlforcada and @mespla have an opinion.

**Comment by mlforcada** [comment]
I'd suggest using the same as Bitextor (GPL v3), or one that is fully compatible.

**Comment by kpu** [comment]
Well, I guess that's one way to ensure big companies will have to pay us to run the software for them.

**Comment by mlforcada** [comment]
Unless they managed to install it by themselves. There would be nothing to prevent them from using it. It's free software

**Comment by lpla** [comment]
In last meeting we agreed to use Apache, as paracrawl/Malign: https://github.com/paracrawl/Malign/blob/master/LICENSE

**Comment by phikoehn** [comment]
Merged the pull request.
